import { Router } from 'express';
import healthCheck from './health-check.js';
import integratedAiRouter from './integrated-ai.js';
import creditsRouter from './credits.js';
import midtransRouter from './midtrans.js';
import userRouter from './user.js';
import ttsRouter from './tts.js';
import referralRouter from './referral.js';
import analyticsRouter from './analytics.js';
import musicRouter from './music.js';
import videoRouter from './video.js';
import imageRouter from './image.js';
import authRouter from './auth.js';
import codeRouter from './code.js';
import textRouter from './text.js';
import imageGenRouter from './image-gen.js';
import imageMultiRouter from './image-multi.js';
import imageGenerationRouter from './image-generation.js';
import dalle2Router from './dalle2.js';
import recaptchaRouter from './recaptcha.js';
import chatRouter from './chat.js';
import claudeRouter from './claude.js';
import testOpenaiRouter from './test-openai.js';

const router = Router();

export default () => {
    router.get('/health', healthCheck);
    router.get('/test-openai', testOpenaiRouter);
    router.use('/integrated-ai', integratedAiRouter);
    router.use('/credits', creditsRouter);
    router.use('/midtrans', midtransRouter);
    router.use('/user', userRouter);
    router.use('/tts', ttsRouter);
    router.use('/referral', referralRouter);
    router.use('/analytics', analyticsRouter);
    router.use('/music', musicRouter);
    router.use('/video', videoRouter);
    router.use('/image', imageRouter);
    router.use('/auth', authRouter);
    router.use('/code', codeRouter);
    router.use('/text', textRouter);
    router.use('/image-gen', imageGenRouter);
    router.use('/image-multi', imageMultiRouter);
    router.use('/image-generation', imageGenerationRouter);
    router.use('/recaptcha', recaptchaRouter);
    router.use('/chat', chatRouter);
    router.use('/chat/claude', claudeRouter);

    return router;
};