import { 
  MessageSquare, Wand2, Volume2, FileText, 
  Clapperboard, Scissors, ImagePlus, ScanSearch, Code2, Music
} from 'lucide-react';

export const toolsConfig = [
  { 
    id: 'text-generator',
    nameKey: 'tools.text_generator', 
    defaultName: 'Text Generator',
    icon: MessageSquare, 
    descKey: 'tools.desc.text_generator',
    defaultDesc: 'Draft articles, emails, and essays. Included in Free plan.', 
    category: 'Text',
    features: ['SEO Optimized', 'Tone Adjustment', 'Multi-lingual'], 
    cost: 2, 
    models: 'GPT-4o, Gemini, Claude', 
    status: 'available',
    href: '/text-generator',
    requiredPlan: 'free',
    availablePlans: ['free', 'professional', 'plus', 'enterprise']
  },
  { 
    id: 'image-generator',
    nameKey: 'tools.image_generator', 
    defaultName: 'Image Generator',
    icon: Wand2, 
    descKey: 'tools.desc.image_generator',
    defaultDesc: 'Generate high-quality images instantly. Included in Free plan.', 
    category: 'Image',
    features: ['DALL-E 3 Support', 'Flux Pro', 'Style Presets'], 
    cost: 5, 
    models: 'OpenAI, Fal AI', 
    status: 'available',
    href: '/image-generator',
    requiredPlan: 'free',
    availablePlans: ['free', 'professional', 'plus', 'enterprise']
  },
  { 
    id: 'video-generator',
    nameKey: 'tools.video_generator', 
    defaultName: 'Video Generator',
    icon: Clapperboard, 
    descKey: 'tools.desc.video_generator',
    defaultDesc: 'Create stunning videos from text prompts. Requires Professional+ plan.', 
    category: 'Video',
    features: ['1080p Resolution', 'Multiple Styles', 'Up to 60s'], 
    cost: 10, 
    models: 'OpenAI, Runway', 
    status: 'available',
    href: '/video-generator',
    requiredPlan: 'professional',
    availablePlans: ['professional', 'plus', 'enterprise']
  },
  { 
    id: 'music-generator',
    nameKey: 'tools.music_generator', 
    defaultName: 'Music Generator',
    icon: Music, 
    descKey: 'tools.desc.music_generator',
    defaultDesc: 'Create original music tracks and audio. Requires Professional+ plan.', 
    category: 'Audio',
    features: ['Multiple Genres', 'Custom BPM', 'Instrumental or Vocal'], 
    cost: 8, 
    models: 'Suno, MusicGen', 
    status: 'available',
    href: '/music-generator',
    requiredPlan: 'professional',
    availablePlans: ['professional', 'plus', 'enterprise']
  },
  { 
    id: 'code-generator',
    nameKey: 'tools.code_generator', 
    defaultName: 'Code Generator',
    icon: Code2, 
    descKey: 'tools.desc.code_generator',
    defaultDesc: 'Write, debug, and refactor code. Requires Professional+ plan.', 
    category: 'Code',
    features: ['Multiple Languages', 'Bug Fixing', 'Code Explanation'], 
    cost: 5, 
    models: 'Deepseek, Claude', 
    status: 'available',
    href: '/code-generator',
    requiredPlan: 'professional',
    availablePlans: ['professional', 'plus', 'enterprise']
  },
  { 
    id: 'text-to-speech',
    nameKey: 'tools.tts', 
    defaultName: 'Text-to-Speech',
    icon: Volume2, 
    descKey: 'tools.desc.tts',
    defaultDesc: 'Convert text to lifelike audio. Requires Plus+ plan.', 
    category: 'Audio',
    features: ['50+ Voices', 'Emotion Control', 'MP3 Export'], 
    cost: 3, 
    models: 'OpenAI TTS', 
    status: 'available',
    href: '/text-to-speech',
    requiredPlan: 'plus',
    availablePlans: ['plus', 'enterprise']
  },
  { 
    id: 'image-analyzer',
    nameKey: 'tools.image_analyzer', 
    defaultName: 'Image Analyzer',
    icon: ScanSearch, 
    descKey: 'tools.desc.image_analyzer',
    defaultDesc: 'Extract insights from any image. Requires Plus+ plan.', 
    category: 'Image',
    features: ['Object Detection', 'Text Extraction', 'Color Analysis'], 
    cost: 3, 
    models: 'GPT-4o Vision', 
    status: 'available',
    href: '/image-analyzer',
    requiredPlan: 'plus',
    availablePlans: ['plus', 'enterprise']
  },
  { 
    id: 'pdf-analyzer',
    nameKey: 'tools.pdf_analyzer', 
    defaultName: 'PDF Analyzer',
    icon: FileText, 
    descKey: 'tools.desc.pdf_analyzer',
    defaultDesc: 'Chat with your PDF documents. Requires Plus+ plan.', 
    category: 'Document',
    features: ['Fast Extraction', 'Summary Generation', 'Citation Links'], 
    cost: 5, 
    models: 'Claude 3.5', 
    status: 'available',
    href: '/pdf-chat',
    requiredPlan: 'plus',
    availablePlans: ['plus', 'enterprise']
  },
  { 
    id: 'video-editor',
    nameKey: 'tools.video_editor', 
    defaultName: 'Video Editor',
    icon: Scissors, 
    descKey: 'tools.desc.video_editor',
    defaultDesc: 'Edit and enhance videos with AI. Requires Enterprise plan.', 
    category: 'Video',
    features: ['Auto-cut', 'Captioning', 'Color Grading'], 
    cost: 8, 
    models: 'Internal', 
    status: 'available',
    href: '/video-editor',
    requiredPlan: 'enterprise',
    availablePlans: ['enterprise']
  },
  { 
    id: 'image-editor',
    nameKey: 'tools.image_editor', 
    defaultName: 'Image Editor',
    icon: ImagePlus, 
    descKey: 'tools.desc.image_editor',
    defaultDesc: 'Modify images with text commands. Requires Enterprise plan.', 
    category: 'Image',
    features: ['Inpainting', 'Background Removal', 'Upscaling'], 
    cost: 4, 
    models: 'Stable Diffusion', 
    status: 'available',
    href: '/image-editor',
    requiredPlan: 'enterprise',
    availablePlans: ['enterprise']
  }
];